### ISSUE TITLE
setActivity

### ISSUE THREAD

**Issue by ipadpuppydogdude1** [HyperCoder2975/HyperCast#3]
There is a setActivity error on start. http://prntscr.com/hr5flr

**Comment by HyperCoder2975** [comment]
Are you using an old version of Discord.JS?

**Comment by YorkAARGH** [comment]
I've just tested this a moment ago, I hope you are aware that there is a small delay from when the bot hits ready and when the status updates, it's about 5 minutes.

As you can see by the attached images that it is clearly working as intended.

![Client Started](http://evie.ban-hammered.me/i/guknc.png)
![Status Updated](http://evie.ban-hammered.me/i/jqoh7.png)

Could you please expand on the issue if possible?

**Comment by DoctorDarkMagic** [comment]
Try running `npm install`, that should update all the packages. You can then run the bot, try this then report back.

**Comment by ipadpuppydogdude1** [comment]
I did. It still came up.

**Comment by DoctorDarkMagic** [comment]
Any logs in the terminal?

**Comment by HyperCoder2975** [comment]
Use the latest version of discord.js. If you get this error, you're not using the latest.

**Comment by ipadpuppydogdude1** [comment]
I am using latest.

**Comment by HyperCoder2975** [comment]
Obviously not. https://discord.js.org/index.html#/docs/main/master/class/ClientUser?scrollTo=setActivity
