### ISSUE TITLE
ffmpeg not found error

### ISSUE THREAD

**Issue by ipadpuppydogdude1** [HyperCoder2975/HyperCast#4]
I did NPM install. Tried a command, and the bot would not respond, or play.

**Comment by HyperCoder2975** [comment]
Try installing ffmpeg on your system.

**Comment by YorkAARGH** [comment]
@ipadpuppydogdude1 please follow one of these guides to get FFMPEG installed and working on your system

 [**Windows**](http://adaptivesamples.com/how-to-install-ffmpeg-on-windows/) :: [**OSX**](http://www.renevolution.com/ffmpeg/2013/03/16/how-to-install-ffmpeg-on-mac-os-x.html) :: [**Linux**](https://www.assetbank.co.uk/support/documentation/install/ffmpeg-debian-squeeze/ffmpeg-debian-jessie/)

**Comment by ipadpuppydogdude1** [comment]
I know but, it will only work on my VPS, but not my PC.

**Comment by HyperCoder2975** [comment]
That's on your end then, not ours.
